name: No Free usage issue checker
on:
  issues:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check issue actor
      uses: fluttercandies/no-free-usage-action@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        forked: --no-forked
        words: To support our project, please file the issue after you starred the repo. Thanks! :)